### ISSUE TITLE
解码报错

### ISSUE THREAD

**Issue by aidaodi** [LiteAVSDK/TRTC_Android#7]
TRTC视频通话时，来电按接听按钮时报错。
![ME@Y(LKA7{JQI}5`%8E(LNX](https://user-images.githubusercontent.com/9432992/185788021-f86eda8f-2ee1-48b3-b201-c25fab8a7431.png)
工作的设备不是正常的手机，是定制的平板。

**Comment by aidaodi** [comment]
摄像头为外接USB摄像头

**Comment by MinTate** [comment]
好的，这个问题我们正在分析~
